### ISSUE TITLE
Cannot compile on OpenBSD/adJ 6.2 

### ISSUE THREAD

**Issue by vtamara** [fireice-uk/xmr-stak-cpu#456]
I could start with:
```sh
cmake -DMICROHTTPD_ENABLE=OFF -DHWLOC_ENABLE=OFF
```

However make generates some errors, the first one:
```sh
/home/vtamara/tmp/xmr-stak-cpu/minethd.cpp:64:2: error: unknown type name 'cpu_set_t'
        cpu_set_t mn;
        ^
/home/vtamara/tmp/xmr-stak-cpu/minethd.cpp:67:35: error: use of undeclared identifier 'cpu_set_t'
        pthread_setaffinity_np(h, sizeof(cpu_set_t), &mn);
                                         ^
2 errors generated.
```

**Comment by psychocrypt** [comment]
please use our latest code base
https://github.com/fireice-uk/xmr-stak/releases
