### ISSUE TITLE
compiling on Mac OS X, almost working

### ISSUE THREAD

**Issue by mdhoenig** [fireice-uk/xmr-stak-cpu#324]
I'm attempting a compile on Mac Pro running Mac OS 10.8.5.  Managed to install `libmicrohttpd` and `hwloc` using MacPorts.

First attempt:

```
> make
[ 38%] Built target xmr-stak-c
[ 44%] Building CXX object CMakeFiles/xmr-stak-cpu.dir/cli-miner.cpp.o
In file included from xmr-stak-cpu/cli-miner.cpp:24:
In file included from xmr-stak-cpu/executor.h:2:
xmr-stak-cpu/thdq.hpp:4:10: fatal error: 'thread' file not found
#include <thread>
         ^
1 error generated.
make[2]: *** [CMakeFiles/xmr-stak-cpu.dir/cli-miner.cpp.o] Error 1
make[1]: *** [CMakeFiles/xmr-stak-cpu.dir/all] Error 2
make: *** [all] Error 2
```

OK, some googling suggests I need to add this line to my `CMakeLists.txt`:
`set(CMAKE_CXX_FLAGS "-std=c++11 -stdlib=libc++")
`

Try again:

```
> make
[ 38%] Built target xmr-stak-c
[ 44%] Building CXX object CMakeFiles/xmr-stak-cpu.dir/cli-miner.cpp.o
[ 50%] Building CXX object CMakeFiles/xmr-stak-cpu.dir/console.cpp.o
[ 55%] Building CXX object CMakeFiles/xmr-stak-cpu.dir/executor.cpp.o
[ 61%] Building CXX object CMakeFiles/xmr-stak-cpu.dir/httpd.cpp.o
[ 66%] Building CXX object CMakeFiles/xmr-stak-cpu.dir/jconf.cpp.o
xmr-stak-cpu/jconf.cpp:273:2: error: use of undeclared identifier '__cpuid_count'
        __cpuid_count(eax, ecx, val[0], val[1], val[2], val[3]);
        ^
1 error generated.
make[2]: *** [CMakeFiles/xmr-stak-cpu.dir/jconf.cpp.o] Error 1
make[1]: *** [CMakeFiles/xmr-stak-cpu.dir/all] Error 2
make: *** [all] Error 2
```

And that's as far as I get.  I followed the tip in #124 to replace `cpu_id` with `static_cast<integer_t>(cpu_id)` in `minethd.cpp`, but I'm not sure what to do about this `__cpuid_count`.

Any ideas?

**Comment by mdhoenig** [comment]
Here is the _cmake_ output:

```
-- The C compiler identification is AppleClang 5.1.0.5030040
-- The CXX compiler identification is AppleClang 5.1.0.5030040
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Found OpenSSL: /opt/local/lib/libcrypto.dylib (found version "1.0.2l") 
-- Configuring done
-- Generating done
-- Build files have been written to: bin/xmr-stak-cpu

```

**Comment by greg3k** [comment]
I've been able to compile fine on mac, just never with libmicrohttpd enabled.
If you disable it, it should compile fine.

https://github.com/fireice-uk/xmr-stak-cpu/issues/311

**Comment by ducho** [comment]
@mdhoenig how u solve this issue? i've same on mac osx sierra.
`
[ 44%] Building CXX object CMakeFiles/xmr-stak-cpu.dir/minethd.cpp.o
/Users/Ducho/Monero/xmr-stak-cpu/minethd.cpp:51:66: error: expected ')'
void thd_setaffinity(std::thread::native_handle_type h, uint64_t static_cast<integer_t>(cpu_id))
                                                                 ^
/Users/Ducho/Monero/xmr-stak-cpu/minethd.cpp:51:21: note: to match this '('
void thd_setaffinity(std::thread::native_handle_type h, uint64_t static_cast<integer_t>(cpu_id))
                    ^
/Users/Ducho/Monero/xmr-stak-cpu/minethd.cpp:55:66: error: use of undeclared identifier 'cpu_id'
        thread_affinity_policy_data_t policy = { static_cast<integer_t>(cpu_id) };

`

**Comment by kth5** [comment]
@ducho I simply used gcc-7 and openssl from homewbrew. Never got it to built an executable properly and when I did once, it wasn't as fast for reasons beyond me.

```
CFLAGS="-Ofast -march=native -mtune=native" CXXFLAGS="${CFLAGS}" CC=gcc-7 CXX=g++-7 cmake . -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl
```

**Comment by ducho** [comment]
@kth5 thanks! 
But when I start the xmr-stack-cpu, I'll see:

`[2017-10-06 20:53:48] : Starting single thread, affinity: 0.
[2017-10-06 20:53:48] : Starting single thread, affinity: 1.
[2017-10-06 20:53:48] : Connecting to pool xmrpool.eu:3333 ...
[2017-10-06 20:53:48] : hwloc: can't bind memory
[2017-10-06 20:53:48] : hwloc: can't bind memory
[2017-10-06 20:53:48] : WARNING on MacOS thread affinity is only advisory.
[2017-10-06 20:53:48] : WARNING on MacOS thread affinity is only advisory.
[2017-10-06 20:53:49] : MEMORY ALLOC FAILED: mmap failed
[2017-10-06 20:53:49] : MEMORY ALLOC FAILED: mmap failed
[2017-10-06 20:53:49] : Connected. Logging in...
[2017-10-06 20:53:49] : Difficulty changed. Now: 5000.
[2017-10-06 20:53:49] : New block detected.
[2017-10-06 20:54:24] : New block detected.
[2017-10-06 20:55:00] : Result accepted by the pool.
` 
Is it OK? Because running 2 days and nothing balance on my wallet. :(

**Comment by mdhoenig** [comment]
@ducho - what kind of processor are you using?  CPU mining is pretty slow.  The output looks OK to me (I get the same warnings but am still accumulating XMR).
