### PR TITLE
Alpine 3.6 compilation errors

### PR DESCRIPTION
**Pull request by fabionitto**
Trying to compile in Alpine 3.6 resulted in errors such as:
```
In file included from /xmr-stak-cpu/jpsock.cpp:33:0:
/xmr-stak-cpu/socks.h: In function 'const char* sock_strerror(char*, size_t)':
/xmr-stak-cpu/socks.h:83:19: error: invalid conversion from 'int' to 'const char*' [-fpermissive]
  return strerror_r(errno, buf, len);
```
and
```
/xmr-stak-cpu/minethd.cpp:56:2: error: 'memset' was not declared in this scope
  CPU_ZERO(&mn);
```

This PR fixes them.

To compile on Alpine 3.6 you need to:
```
# apk update
# apk add make cmake g++ libmicrohttpd-dev openssl-dev
$ cmake .
$ make install
```

### CODE REVIEW

**Comment by psychocrypt** [comment]
please reopen a new pull request against the dev branch. The master branch is only for stable change (dev is merged to master to create a release)

**Comment by psychocrypt** [comment]
Please also rebase against the dev branch, it could be that the changes are already in the dev branch.
