### ISSUE TITLE
3 cores better perforamce than 4

### ISSUE THREAD

**Issue by LexPrima** [fireice-uk/xmr-stak-cpu#175]
I have an Intel IvyBridge i7 3770K
When I run it on 3 cores I get about 70H/s per core but when I run it on 4 cores it drops do 50H/s per core.

**Comment by Hongi** [comment]
Same problem here !

I have two processors Intel Xeon E5 2420 (6 core 12thread)
So the best configuration should be :

`"cpu_threads_conf" :
[
   { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 0 },
   { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 1 },
   { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 2 },
   { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 3 },
   { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 4 },
   { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 5 },
   { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 6 },
   { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 7 },
   { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 8 },
   { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 9 },
   { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 10 },
   { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 11 },
],



The best configuration i can get is about 220H/s with about 16H/s by core 
This is my configuration, i try everything between 6 and 20 :
`"cpu_threads_conf" :
[
   { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 0 },
   { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 1 },
   { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 2 },
   { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 3 },
   { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 4 },
   { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 5 },
   { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 6 },
   { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 7 },
   { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 8 },
   { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 9 },
   { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 10 },
   { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 11 },
   { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 12 },
   { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 13 },
   { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 14 },
   { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 15 },
],
`


Am i missing something ?

**Comment by uaktags** [comment]
Can't you only use half of whatever your L3 is (atleast for best results?). 
For instance, on my AMD 1800x, my best results are with 7 (1,3,5,7,9,11,13) since I only have 16MB of L3. If I go higher, my per core Hash goes from ~70 to 50 per core, and I drop from ~450h/s to ~330, and then further down we go.

```
HASHRATE REPORT
| ID | 2.5s |  60s |  15m | ID | 2.5s |  60s |  15m |
|  0 | 63.6 | 62.9 | (na) |  1 | 68.2 | 62.4 | (na) |
|  2 | 61.4 | 62.7 | (na) |  3 | 68.4 | 59.7 | (na) |
|  4 | 68.0 | 60.3 | (na) |  5 | 68.2 | 60.7 | (na) |
|  6 | 68.1 | 59.2 | (na) |
-----------------------------------------------------
Totals:   466.0 428.0 (na) H/s
Highest:  456.5 H/s
```
vs
```
HASHRATE REPORT
| ID | 2.5s |  60s |  15m | ID | 2.5s |  60s |  15m |
|  0 | 40.9 | 52.7 | (na) |  1 | 39.7 | 52.4 | (na) |
|  2 | 45.5 | 51.5 | (na) |  3 | 38.3 | 49.7 | 51.2 |
|  4 | 40.5 | 50.9 | (na) |  5 | 43.0 | 51.5 | (na) |
|  6 | 44.1 | 51.0 | (na) |  7 | 39.4 | 50.4 | (na) |
-----------------------------------------------------
Totals:   331.4 410.1 (na) H/s
Highest:  467.2 H/s
```

So for the Xeon, I'd probably would have done 0-18 even numbers (0,2,4,6,8,...,18)[10total] rather than the (0-11) [12 threads total]

My i7-2600K (8M) doing 0-3 rather than doing only 3 of the 4:
```
HASHRATE REPORT
| ID | 2.5s |  60s |  15m | ID | 2.5s |  60s |  15m |
|  0 | 56.9 | 57.1 | 57.1 |  1 | 58.0 | 58.4 | 58.4 |
|  2 | 56.9 | 57.1 | 57.1 |  3 | 58.0 | 58.4 | 58.4 |
-----------------------------------------------------
Totals:   229.9 231.0 231.0 H/s
Highest:  234.7 H/s
```
Dropping down by 1:
```
HASHRATE REPORT
| ID | 2.5s |  60s |  15m | ID | 2.5s |  60s |  15m |
|  0 | 69.4 | 69.7 | (na) |  1 | 80.7 | 81.1 | (na) |
|  2 | 69.4 | 69.7 | (na) |
-----------------------------------------------------
Totals:   219.6 220.5 (na) H/s
Highest:  222.7 H/s
```

**Comment by Hongi** [comment]
With the current config : (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15) for two E5-2420 15MB

HASHRATE REPORT
| ID | 2.5s |  60s |  15m | ID | 2.5s |  60s |  15m |
|  0 | 13.3 | 13.4 | (na) |  1 | 13.8 | 13.7 | (na) |
|  2 | 13.6 | 13.6 | (na) |  3 | 13.7 | 13.6 | (na) |
|  4 | 17.3 | 17.2 | (na) |  5 | 16.7 | 16.8 | (na) |
|  6 | 17.3 | 17.4 | (na) |  7 | 17.3 | 16.9 | (na) |
|  8 | 17.4 | 17.6 | (na) |  9 | 17.4 | 17.2 | (na) |
| 10 | 17.7 | 17.8 | (na) | 11 | 17.7 | 17.5 | (na) |
| 12 | 13.4 | 13.4 | (na) | 13 | 13.8 | 13.7 | (na) |
| 14 | 13.6 | 13.6 | (na) | 15 | 13.7 | 13.6 | (na) |
-----------------------------------------------------
Totals:   247.6 247.0 (na) H/s
Highest:  250.7 H/s

With the recommanded configuration : (0,2,4,6,8,10,12,14,16,18)
HASHRATE REPORT
| ID | 2.5s |  60s |  15m | ID | 2.5s |  60s |  15m |
|  0 | 11.8 | 12.0 | (na) |  1 | 11.7 | 11.8 | (na) |
|  2 | 11.7 | 11.7 | (na) |  3 | 11.7 | 11.7 | (na) |
|  4 | 15.0 | 15.1 | (na) |  5 | 15.4 | 15.5 | (na) |
|  6 | 11.8 | 12.0 | (na) |  7 | 11.5 | 11.7 | (na) |
|  8 | 11.7 | 11.7 | (na) |  9 | 11.7 | 11.7 | (na) |
-----------------------------------------------------
Totals:   124.1 125.0 (na) H/s
Highest:  125.8 H/s

**Comment by psychocrypt** [comment]
@Hongi please post all miner output it looks like there is no aes-ni used

**Comment by Hongi** [comment]
I'm not sur of what you need, so here is my output :

> -------------------------------------------------------------------
    [2017-06-30 09:40:15] : Starting single thread, affinity: 0.
    [2017-06-30 09:40:15] : Starting single thread, affinity: 1.
    [2017-06-30 09:40:15] : Starting single thread, affinity: 2.
    [2017-06-30 09:40:15] : Starting single thread, affinity: 3.
    [2017-06-30 09:40:15] : Starting single thread, affinity: 4.
    [2017-06-30 09:40:15] : Starting single thread, affinity: 5.
    [2017-06-30 09:40:15] : Starting single thread, affinity: 6.
    [2017-06-30 09:40:15] : Starting single thread, affinity: 7.
    [2017-06-30 09:40:15] : Starting single thread, affinity: 8.
    [2017-06-30 09:40:15] : Starting single thread, affinity: 9.
    [2017-06-30 09:40:15] : Starting single thread, affinity: 10.
    [2017-06-30 09:40:15] : Starting single thread, affinity: 11.    
    [2017-06-30 09:40:15] : Starting single thread, affinity: 12.
    [2017-06-30 09:40:15] : Starting single thread, affinity: 13.
    [2017-06-30 09:40:15] : Starting single thread, affinity: 14.
    [2017-06-30 09:40:15] : Starting single thread, affinity: 15.
    [2017-06-30 09:40:15] : Connecting to pool xmr.crypto-pool.fr:3333 ...
    [2017-06-30 09:40:15] : Connected. Logging in...
    [2017-06-30 09:40:15] : Difficulty changed. Now: 18000.
    [2017-06-30 09:40:15] : New block detected.
    HASHRATE REPORT
    | ID | 2.5s |  60s |  15m | ID | 2.5s |  60s |  15m |
    |  0 | 13.8 | (na) | (na) |  1 | 14.0 | (na) | (na) |
    |  2 | 13.7 | (na) | (na) |  3 | 13.9 | (na) | (na) |
    |  4 | 17.2 | (na) | (na) |  5 | 17.8 | (na) | (na) |
    |  6 | 17.4 | (na) | (na) |  7 | 17.8 | (na) | (na) |
    |  8 | 17.6 | (na) | (na) |  9 | 18.0 | (na) | (na) |
    | 10 | 17.8 | (na) | (na) | 11 | 18.2 | (na) | (na) |
    | 12 | 13.8 | (na) | (na) | 13 | 14.0 | (na) | (na) |
    | 14 | 13.3 | (na) | (na) | 15 | 13.8 | (na) | (na) |
    -----------------------------------------------------
    Totals:   252.0 (na) (na) H/s
    Highest:  0.0 H/s


And here is my config.txt file :

> "cpu_threads_conf" :
   [
      { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 0 },
      { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 1 },
      { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 2 },
      { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 3 },
      { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 4 },
      { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 5 },
      { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 6 },
      { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 7 },
      { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 8 },
      { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 9 },
      { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 10 },
      { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 11 },
      { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 12 },
      { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 13 },
      { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 14 },
      { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 15 },
   ],

   "use_slow_memory" : "warn",
   "nicehash_nonce" : false,
   "use_tls" : false,
   "tls_secure_algo" : true,
   "tls_fingerprint" : "",
   "pool_address" : "xmr.crypto-pool.fr:3333",
   "wallet_address" : "43rLq1WVWuy8DhZoajCD...fDr1u9UXYHQBhvMp8a91dNQEyyNdt",
   "pool_password" : "x",
   "call_timeout" : 10,
   "retry_time" : 10,
   "giveup_limit" : 0,
   "verbose_level" : 4,
   "h_print_time" : 600,
   "output_file" : "/opt/XMR/log.txt",
   "httpd_port" : 0,
   "prefer_ipv4" : true,

**Comment by psychocrypt** [comment]
@Hongi could you please compile the current dev branch with hwloc. Than please start with a config from the reposetory. The newest version will analyse your system and will create a nearly optimal config for your. Hwloc nows if odd or even core IDs are native cores. It is hard to check if you have configuard the core ids wrong or if the current hash rate is the max.

Do you running everything in a VM or on a native system.

**Comment by psychocrypt** [comment]
@Hongi Could it be that you still cut some lines from the output. I miss at least one line at the top but maybe some more. Please post everything including the start command, than I know that no lines are missing.

**Comment by Hongi** [comment]
Ok i will do it from scratch and documenting everything, it can be used by someone else :

I'm working on CentOS 6.8 "minimal"

**Installation**

yum install -y vim git cmake3 centos-release-scl libmicrohttpd-devel hwloc-devel libmicrohttpd-devel openssl-devel
yum install -y devtoolset-4-gcc*
git clone -b dev https://github.com/fireice-uk/xmr-stak-cpu
cd xmr-stak-cpu/
scl enable devtoolset-4 bash
cmake3 .
make install


**Error**

[ 36%] Built target xmr-stak-c
[ 42%] Linking CXX executable bin/xmr-stak-cpu
libxmr-stak-c.a(soft_aes.c.o): In function `soft_aeskeygenassist':
soft_aes.c:(.text+0x3ff): undefined reference to `_rotr'
soft_aes.c:(.text+0x426): undefined reference to `_rotr'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/xmr-stak-cpu] Error 1
make[1]: *** [CMakeFiles/xmr-stak-cpu.dir/all] Error 2
make: *** [all] Error 2

**Comment by ruzickap** [comment]
Hello.

I tried the steps above with CentOS 7.x and they are working fine - compilation finished without errors. I can not confirm this will work with CentOS 6.x.

Can you use CentOS7 ?

**Comment by ruzickap** [comment]
I also tried the steps on CentOS 6.9 and it's working fine too. Can you try co install fresh CentOS 6.9 upgrade all packages and try it again?

**Comment by systemroot** [comment]
i have a server with 
4 Cores / 8 Threads. 

and when i use those 8 all i get 90-100H/s . but when i use just 4 i get 250H/s 
did you got that maybe you are using all threads and not only cores?!

**Comment by Hongi** [comment]
Ok let's resume 
**Build on CentOS 7, run on CentOS 7 **

It is working well with 1 CPU, but still strange for the configuration with 2 CPU

Test on _two_  E5-2650 v3 
Recommended configuration by XMR : (0,1,2.........1è,18,19) Hashrate = 250
Custom configuration : (0,1,2............34,35,36) Hashrate = 430

1 Error : Huge Page :
`sysctl -w vm.nr_hugepages=128`
sysctl : cannot stat  /proc/sys/vm/nr_hugepages: No file or directory


** Build on CentOS 7, run on CentOS 6**
Not working, error : `/usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14'`


** Build on CentOS 6.9 (updated), run on CentOS 6**
I have to try this now :)

**Comment by systemroot** [comment]
>Error : Huge Page :
sysctl -w vm.nr_hugepages=128
sysctl : cannot stat  /proc/sys/vm/nr_hugepages: No file or directory

https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Virtualization_Tuning_and_Optimization_Guide/sect-Virtualization_Tuning_Optimization_Guide-Memory-Tuning.html

**Comment by psychocrypt** [comment]
@Hongi to run contos7 binary on older systems you need to compile static. Please try ccmake . in the build directory or follow the readme.md.

Please post the full thread config of the miner suggested configuration. 

Please also run `hwloc-ls --output-format ascii` and post the output

**Comment by Hongi** [comment]
Ok, everything is working now !

> Compilation
    yum install -y vim git cmake3 centos-release-scl libmicrohttpd-devel hwloc-devel libmicrohttpd-devel 
    openssl-devel
    yum install -y devtoolset-4-gcc*
    git clone -b dev https://github.com/fireice-uk/xmr-stak-cpu
    cd xmr-stak-cpu/
    scl enable devtoolset-4 bash
    cmake3 -DCMAKE_LINK_STATIC=ON .
    make install

Usage 

> yum install -y hwloc-devel libmicrohttpd-devel openssl-devel
    sysctl -w vm.nr_hugepages=128
    echo "* soft memlock 262144" >> /etc/security/limits.conf
    echo "* hard memlock 262144" >> /etc/security/limits.conf

Test on two E5-2650 v3

- Recommended configuration by XMR : (0,1,2.........17,18,19) Hashrate = 750

Thank you all !

**Comment by AlexMalex** [comment]
Hongi, 
is 750 H/s for only one E5-2650 v3 or both CPUs?

**Comment by Hongi** [comment]
On both

**Comment by psychocrypt** [comment]
@Hongi If you start with the auto suggested config you could try to remove one times per cpu socket the low power mode in the config. This means you will have 2 MiB cache per socket free, this will sometimes increase the hash rate a little bit.

**Comment by Hongi** [comment]
Yes you was right i up from 750 to 800 !

**Comment by psychocrypt** [comment]
@LexPrima To answer the initial question. The small performance drop can happen because each thread needs 2MiB to hold the scratchpad memory and than a view kilo byte for additional data. I
In your case it would be interesting if you pinned the threads correct. If so than the little amount of extra data decreased your performance.

I will close this issue, if there are more questions I can reopen it.

**Comment by LexPrima** [comment]
Is this inavoidable? I mean
3 Cores x 79 H/s = 240 H/s
4 Cores x 59 H/s = 236 H/s
Then I'm better off using only 3 cores since better mining performance also 1 core left for desktop reserve?
